version: '3.8'

services:
  portfolio:
    container_name: portfolio_kalvin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # - RESEND_API_KEY=${RESEND_API_KEY} # Décommentez pour injecter une clé API Email
    # volumes:
    #  - ./.env.local:/app/.env.local # Décommentez pour utiliser le fichier .env local
